import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {pbkdf2Sync} from 'node:crypto';
import worker,{normalize,newCode,hash,verifyPassword} from '../dist/server/index.js';
const origin='https://endry.test';
function setup(){
 const sqlite=new DatabaseSync(':memory:');sqlite.exec(readFileSync(new URL('../drizzle/0000_wise_caretaker.sql',import.meta.url),'utf8'));
 function statement(query,args=[]){return {bind(...a){return statement(query,a)},async first(){return sqlite.prepare(query).get(...args)||null},async all(){return {results:sqlite.prepare(query).all(...args)}},async run(){return sqlite.prepare(query).run(...args)}};}
 const files=new Map(),env={ADMIN_AUTH_MODE:'sites',ADMIN_EMAIL:'owner@example.test',DB:{prepare:statement,async batch(list){sqlite.exec('BEGIN');try{const out=[];for(const s of list)out.push(await s.run());sqlite.exec('COMMIT');return out}catch(e){sqlite.exec('ROLLBACK');throw e}}},BUCKET:{async put(key,bytes){files.set(key,bytes)},async get(key){return files.has(key)?{body:files.get(key)}:null},async delete(key){files.delete(key)}}};
 let ip=0;const deferred=[];
 async function call(path,{method='GET',data,cookie,owner=false,headers={},raw}={}){const r=await worker.fetch(new Request(origin+path,{method,headers:{origin,'cf-connecting-ip':'192.0.2.'+(++ip),...(data?{'content-type':'application/json'}:{}),...(owner?{'oai-authenticated-user-id':'owner','oai-authenticated-user-email':'owner@example.test'}:{}),...(cookie?{cookie}:{}),...headers},body:raw??(data?JSON.stringify(data):undefined)}),env,{waitUntil(p){deferred.push(p)}});const content=r.headers.get('content-type')||'';const result=content.includes('json')?await r.json():await r.arrayBuffer();return {status:r.status,data:result,headers:r.headers,cookie:r.headers.get('set-cookie')?.split(';')[0]};}
 async function create(name='Client A'){return (await call('/api/admin/projects',{method:'POST',owner:true,data:{title:'Chantier test',client:name,location:'Bussy'}})).data;}
 async function login(code){return call('/api/login',{method:'POST',data:{code}});}
 return {env,sqlite,files,call,create,login};
}
test('codes aléatoires, normalisation et empreinte seulement',async()=>{const codes=new Set(Array.from({length:1000},newCode));assert.equal(codes.size,1000);for(const c of codes)assert.match(c,/^[A-HJ-NP-Z2-9]{5}(?:-[A-HJ-NP-Z2-9]{5}){3}$/);const t=setup(),p=await t.create();const stored=t.sqlite.prepare('SELECT * FROM projects').get();assert.equal(stored.code_hash,await hash(normalize(p.code)));assert.ok(!JSON.stringify(stored).includes(p.code));assert.equal((await t.login(p.code.toLowerCase())).status,200);assert.equal((await t.login(p.code)).status,200);});
test('isolation des chantiers et photos, pas d’accès admin client',async()=>{const t=setup(),a=await t.create(),b=await t.create('Client B');const ca=(await t.login(a.code)).cookie,cb=(await t.login(b.code)).cookie;assert.equal((await t.call('/api/chantier')).status,401);assert.equal((await t.call('/api/admin/projects',{cookie:ca})).status,403);const photo=await t.call('/api/admin/projects/'+a.id+'/photos',{method:'POST',owner:true,raw:new Uint8Array([255,216,255,0,0])});assert.equal(photo.status,201);assert.equal((await t.call('/api/photos/'+photo.data.id,{cookie:ca})).status,200);assert.equal((await t.call('/api/photos/'+photo.data.id,{cookie:cb})).status,404);assert.equal((await t.call('/api/photos/'+photo.data.id)).status,401);assert.equal((await t.call('/api/chantier',{cookie:cb})).data.project.id,b.id);});
test('rotation invalide le code et les sessions, accès désactivable',async()=>{const t=setup(),p=await t.create(),c=(await t.login(p.code)).cookie;const replacement=await t.call('/api/admin/projects/'+p.id+'/code',{method:'POST',owner:true,data:{}});assert.equal((await t.login(p.code)).status,401);assert.equal((await t.call('/api/chantier',{cookie:c})).status,401);const next=(await t.login(replacement.data.code)).cookie;assert.equal((await t.call('/api/chantier',{cookie:next})).status,200);await t.call('/api/admin/projects/'+p.id,{method:'PATCH',owner:true,data:{title:'A',client:'A',location:'',progress:100,status:'Terminé',active:false}});assert.equal((await t.login(replacement.data.code)).status,401);assert.equal((await t.call('/api/chantier',{cookie:next})).status,401);});
test('avancement, nouvelles et suppression de photo',async()=>{const t=setup(),p=await t.create(),c=(await t.login(p.code)).cookie;assert.equal((await t.call('/api/admin/projects/'+p.id,{method:'PATCH',owner:true,data:{title:'Rénovation',client:'A',location:'Bussy',progress:65,status:'En cours',active:true}})).status,200);await t.call('/api/admin/projects/'+p.id+'/updates',{method:'POST',owner:true,data:{body:'Réseaux posés.'}});const d=await t.call('/api/chantier',{cookie:c});assert.equal(d.data.project.progress,65);assert.equal(d.data.updates[0].body,'Réseaux posés.');assert.equal(d.data.project.code_hash,undefined);const photo=await t.call('/api/admin/projects/'+p.id+'/photos',{method:'POST',owner:true,raw:new Uint8Array([255,216,255,0])});assert.equal(t.files.size,1);assert.equal((await t.call('/api/admin/photos/'+photo.data.id,{method:'DELETE',owner:true})).status,200);assert.equal(t.files.size,0);assert.equal((await t.call('/api/photos/'+photo.data.id,{cookie:c})).status,404);});
test('protection CSRF, format de photos, validation et débit',async()=>{const t=setup();assert.equal((await t.call('/api/admin/projects',{method:'POST',owner:true,data:{},headers:{origin:'https://evil.test'}})).status,403);const p=await t.create();assert.equal((await t.call('/api/admin/projects/'+p.id+'/photos',{method:'POST',owner:true,raw:'<svg onload="alert(1)"></svg>'})).status,415);assert.equal((await t.call('/api/admin/projects/'+p.id,{method:'PATCH',owner:true,data:{progress:101}})).status,400);let r;for(let i=0;i<11;i++)r=await t.call('/api/login',{method:'POST',data:{code:'wrong'},headers:{'cf-connecting-ip':'192.0.2.250'}});assert.equal(r.status,429);});
test('connexion autonome refuse les en-têtes Sites et invalide les sessions au changement du secret',async()=>{const t=setup(),salt='0123456789abcdef0123456789abcdef',password='a-very-long-test-passphrase';const digest=pbkdf2Sync(password,Buffer.from(salt,'hex'),100000,32,'sha256').toString('hex');t.env.ADMIN_AUTH_MODE='password';t.env.ADMIN_PASSWORD_HASH=`pbkdf2-sha256$100000$${salt}$${digest}`;assert.equal(await verifyPassword(password,t.env.ADMIN_PASSWORD_HASH),true);assert.equal(await verifyPassword('wrong',t.env.ADMIN_PASSWORD_HASH),false);assert.equal((await t.call('/api/admin/me',{owner:true})).status,403);const r=await t.call('/api/admin-login',{method:'POST',data:{password}});assert.equal(r.status,200);assert.equal((await t.call('/api/admin/me',{cookie:r.cookie})).status,200);t.env.ADMIN_PASSWORD_HASH+='0';assert.equal((await t.call('/api/admin/me',{cookie:r.cookie})).status,403);});
test('pages, contacts et en-têtes de confidentialité',async()=>{const t=setup();for(const path of ['/','/suivi','/admin','/portail.css','/portail.js','/assets/logo.png'])assert.equal((await t.call(path)).status,200);const p=await t.create(),r=await t.login(p.code);assert.match(r.headers.get('set-cookie'),/Secure; HttpOnly; SameSite=Strict/);assert.equal(r.headers.get('cache-control'),'private, no-store');assert.equal(r.headers.get('referrer-policy'),'no-referrer');const page=Buffer.from((await t.call('/')).data).toString();assert.match(page,/026 663 30 60/);assert.match(page,/Dépannage/);assert.match(page,/href="\/suivi"/);});
test('maquettes de variantes servies en privé',async()=>{const t=setup();const moved=await t.call('/variantes');assert.equal(moved.status,301);const index=await t.call('/variantes/');assert.equal(index.status,200);assert.match(Buffer.from(index.data).toString(),/noindex,nofollow/);for(const page of ['a-nocturne','b-atelier','c-monolithe','d-lumiere']){const r=await t.call('/variantes/'+page+'.html');assert.equal(r.status,200);const html=Buffer.from(r.data).toString();assert.match(html,/noindex,nofollow/);assert.match(html,/026 663 30 60/);assert.match(html,/id="depannage"/);assert.match(html,/id="project-form"/);}const font=await t.call('/variantes/fonts/manrope-400.woff2');assert.equal(font.status,200);assert.equal(font.headers.get('content-type'),'font/woff2');});
